---
title: "Roe Deer Movement Data"
subtitle: "Prediction of future movement in Roe Deer"
author: "Tim Fässler and Gregory Biland"
date: "5/3/2022"
output:
  html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r message=FALSE, warning=FALSE, =FALSE, include=FALSE}
Sys.setenv(LANG = "en")
library(readr)  # to import tabular data (e.g. csv)
library(tidyr)
library(dplyr)        # to manipulate (tabular) data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
library(grid)
library(gridExtra)
library(ggplot2)
library(randomNames)
library(caTools)
library(caret)
library(neuralnet)
library(trajr)

knitr::opts_chunk$set(
  message = F,
  fig.width = 7,
  fig.height = 6,
  pandoc.stack.size = "4g",
  fig.align = 'center',
  opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
)

dataFolder   <- here::here()   
RFolder      <- here::here()         
figureFolder <- here::here("figs") 
```

```{r include=FALSE}
deer <- read_delim(file.path(dataFolder, "all_deer_complete.csv")) %>% data.frame()
canton_zh <- st_read(file.path(dataFolder,"Gemeindegrenzen_-OGD/UP_KANTON_F.shp"))
# ASTK <- read_delim(file.path(dataFolder, "Arealstatistik.csv"))
ASTK_ZH <- read_delim(file.path(dataFolder, "ASTK_ZH.csv"))
```
## Abstract

## Introduction

```{r}
#deer <- deer %>% group_by(reh) %>% mutate(Name = randomNames(reh, ethnicity = 4)) #Give deer names
canton_zh <- canton_zh %>% subset(KANTON == "Zürich")
canton_zh <- canton_zh %>% st_transform(2056)

# ASTK <- ASTK %>% st_as_sf(coords = c("E", "N"), crs = 2056, remove = FALSE)
# ASTK_ZH <- st_join(canton_zh, ASTK, join = st_contains_properly, left=TRUE)
# ASTK_ZH <- ASTK_ZH %>% st_drop_geometry()
# write.csv(ASTK_ZH, file = "ASTK_ZH.csv", row.names=FALSE)


# Sex to binary: male = 0, female = 1, rename "reh" to "TierID"
deer$sex[deer$sex == "m"] <- 0
deer$sex[deer$sex == "f"] <- 1
deer <- deer %>% rename(TierID = reh, DatetimeUTC = datetime_utc, N = x, E = y)

deer <- deer %>% mutate(
  E = E + 2000000,
  N = N + 1000000
) %>% subset(select = -c(longitude, latitude))

```

## Material and Methods

### Geometry calculations

```{r}
deer <- deer %>% group_by(TierID) %>% mutate(
  timelag = as.integer(difftime(lead(DatetimeUTC),DatetimeUTC)), #timelag is in minutes
  steplength = sqrt((E - lead(E,1))^2+ (N - lead(N,1))^2))

deer <- deer %>% mutate(speed = (steplength / timelag)*3.6) #km/h
deer <- deer %>% drop_na() %>% data.frame()

#Sinuosity
deer <- TrajFromCoords(deer) %>% subset(select = -c(DatetimeUTC))
deer <- TrajSmoothSG(deer, 3, 101)


characteriseTrajectory <- function(deer) {
  # Measures of speed
  derivs <- TrajDerivatives(deer)
  mean_speed <- mean(derivs$speed)
  sd_speed <- sd(derivs$speed)

  # Measures of straightness
  sinuosity <- TrajSinuosity(deer)
  resampled <- TrajRediscretize(deer, .001)
  Emax <- TrajEmax(resampled)

  # Periodicity
  corr <- TrajDirectionAutocorrelations(resampled, 60)
  first_min <- TrajDAFindFirstMinimum(corr)

  # Return a list with all of the statistics for this trajectory
  list(sd_speed = sd_speed,
       sinuosity = sinuosity,
       Emax = Emax,
       min_deltaS = first_min[1],
       min_C = first_min[2]
  )
}

# Calculate all stats for trajectories in the list
# which was built in the previous example

deer <- TrajsMergeStats(deer, characteriseTrajectory)

```

```{r}
# Resample to 30 seconds steps
deer_resampled <- TrajResampleTime(deer, 0.01)
deer_resampled <- TrajFromCoords(deer_resampled)
```

### Visualization

```{r}
deer <- deer %>% st_as_sf(coords = c("x", "y"), crs = 2056, remove = FALSE)

ggplot()+
  geom_line(data = deer, aes(x=DatetimeUTC, y = speed, col= TierID))+
  ggtitle("Monitoring timespan for 15 different roe deer")+
  ylab("Deer")+
  xlab("Date")

ggplot()+
  geom_sf(data = canton_zh, fill = alpha("white", .1))+
  geom_path(data = deer, aes(x = E, y = N, col = TierID), alpha = 0.3)+
  geom_point(data = deer, aes(x = E, y = N, col = TierID), size = .1)+
  coord_sf(datum = 2056)+
  theme_minimal()+
  ggtitle("Tracking points for 15 different roe deer")

deer <- deer %>% st_drop_geometry()

```

```{r Test and Trainigdata}

#Create training and test data with 80/20% ratio
set.seed(54)
sample <- sample.int(n = nrow(deer), size = floor(0.8*nrow(deer)), replace = F)
trainingset <- deer[sample, ]
testset  <- deer[-sample, ]

trainingset_clean <- select(trainingset, -c(DatetimeUTC, latitude, longitude)) %>% na.omit()
testset_clean <- select(testset, -c(DatetimeUTC, latitude, longitude)) %>% na.omit()
```

### Artificial neural network 
```{r ANN}
set.seed(54)

ann_model <- train(E + N ~ ., data= trainingset_clean, method="nnet", maxit = 1, trace=FALSE, MaxNWts=2600)
ann_model
plot(ann_model)

# Second ANN method

nn=neuralnet(E + N ~ .,data=trainingset_clean, hidden=3,act.fct = "logistic", 
                linear.output = FALSE)
plot(nn)


```
```{r}
trj <- TrajGenerate()

# Smooth before calculating derivatives
smoothed <- TrajSmoothSG(trj, 3, 101)

# Calculate speed and acceleration
derivs <- TrajDerivatives(smoothed)

```



## Results


## Discussion
